"""API-wide constant definitions."""

from .responses import (
    DEFAULT_ERROR_RESPONSES,
    ERROR_DESCRIPTIONS,
    INTERNAL_SERVER_ERROR_RESPONSE,
    NOT_FOUND_RESPONSE,
    ResponseDict,
    UNAUTHORIZED_RESPONSE,
)

__all__ = [
    "DEFAULT_ERROR_RESPONSES",
    "ERROR_DESCRIPTIONS",
    "INTERNAL_SERVER_ERROR_RESPONSE",
    "NOT_FOUND_RESPONSE",
    "ResponseDict",
    "UNAUTHORIZED_RESPONSE",
]
